version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: prettier
    versions:
    - 2.2.1
